import './globals.css';

export const metadata = {
  title: "FGR 6.0",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="favicon.ico" />
        
      </head>
      <body style={{ fontFamily: 'Stick No Bills, sans-serif' }}>
        {children}
      </body>
    </html>
  );
}
